#!/bin/bash
# Repo Harness Scaffold Script
# Generated by repo-harness
# Usage: bash init-project.sh [project-name] [stack]

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Default values
PROJECT_NAME="${1:-my-project}"
STACK="${2:-vite-tanstack}"
PKG_MANAGER="${3:-bun}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PI_LIB_DIR="$SCRIPT_DIR/lib"
if [[ -f "$PI_LIB_DIR/project-init-lib.sh" ]]; then
    # shellcheck source=/dev/null
    . "$PI_LIB_DIR/project-init-lib.sh"
fi
ASSETS_REF_DIR="$SCRIPT_DIR/../assets/reference-configs"
ASSETS_HOOKS_DIR="$SCRIPT_DIR/../assets/hooks"
ASSETS_TEMPLATES_DIR="$SCRIPT_DIR/../assets/templates"
ASSETS_FACTOR_FACTORY_DIR="$ASSETS_TEMPLATES_DIR/factor-factory"
ASSETS_WORKFLOW_CONTRACT="$SCRIPT_DIR/../assets/workflow-contract.v1.json"

echo -e "${BLUE}=== Repo Harness Scaffold ===${NC}"
echo -e "Project: ${GREEN}$PROJECT_NAME${NC}"
echo -e "Stack: ${GREEN}$STACK${NC}"
echo -e "Package Manager: ${GREEN}$PKG_MANAGER${NC}"
echo ""

# Function to check if command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

install_hook_settings_template() {
    pi_print_codex_hook_trust_notice
}

ensure_runtime_gitignore_block() {
    local file_path="$1"
    local extra_entries=""
    if pi_should_enable_factor_factory "$(pi_plan_type "$STACK")"; then
        extra_entries="$(pi_factor_factory_gitignore_entries)"
    fi
    pi_ensure_gitignore_block "$file_path" "" "$extra_entries" "apply"
}

ensure_gitignore_entry() {
    local file_path="$1"
    local entry="$2"
    if ! grep -Fxq "$entry" "$file_path"; then
        printf "%s\n" "$entry" >> "$file_path"
    fi
}

install_hook_assets() {
    pi_install_hook_assets "$PWD" "$ASSETS_HOOKS_DIR" "apply"
    echo -e "${GREEN}Repo-local hook fallback installed to .ai/hooks/${NC}"
}

install_workflow_contract() {
    pi_install_workflow_contract "$PWD" "$ASSETS_WORKFLOW_CONTRACT" "apply"
}

create_contract_directories() {
    while IFS= read -r rel_dir; do
        [ -z "$rel_dir" ] && continue
        mkdir -p "$rel_dir"
    done < <(pi_workflow_contract_query_lines "$ASSETS_WORKFLOW_CONTRACT" "artifacts.requiredDirectories")
}

ensure_task_sync_package_script() {
    pi_ensure_task_sync "$PWD" "0" "apply" || {
        echo -e "${YELLOW}Warning: task workflow script injection failed for package.json.${NC}"
    }
}

# Check package manager
check_package_manager() {
    case $PKG_MANAGER in
        bun)
            if ! command_exists bun; then
                echo -e "${YELLOW}Bun not found. Installing...${NC}"
                curl -fsSL https://bun.sh/install | bash
            fi
            ;;
        pnpm)
            if ! command_exists pnpm; then
                echo -e "${YELLOW}pnpm not found. Installing...${NC}"
                npm install -g pnpm
            fi
            ;;
        npm)
            # npm comes with Node.js
            ;;
    esac
}

# Create project based on stack
create_project() {
    case $STACK in
        vite-tanstack)
            echo -e "${BLUE}Creating Vite + TanStack Router project...${NC}"
            if [ "$PKG_MANAGER" = "bun" ]; then
                bun create vite "$PROJECT_NAME" -- --template react-ts
            else
                $PKG_MANAGER create vite@latest "$PROJECT_NAME" -- --template react-ts
            fi
            cd "$PROJECT_NAME"

            # Install TanStack Router
            $PKG_MANAGER add @tanstack/react-router
            $PKG_MANAGER add -D @tanstack/router-devtools @tanstack/router-plugin

            # Install TanStack Query
            $PKG_MANAGER add @tanstack/react-query
            $PKG_MANAGER add -D @tanstack/react-query-devtools

            # Install shadcn/ui
            npx shadcn@latest init -y
            npx shadcn@latest add button input table form dialog select card tabs

            # Install additional deps
            $PKG_MANAGER add @supabase/supabase-js zustand
            $PKG_MANAGER add react-hook-form @hookform/resolvers zod
            $PKG_MANAGER add clsx tailwind-merge lucide-react date-fns
            ;;

        remix)
            echo -e "${BLUE}Creating Remix project...${NC}"
            npx create-remix@latest "$PROJECT_NAME" --yes
            cd "$PROJECT_NAME"

            # Install shadcn/ui
            npx shadcn@latest init -y
            npx shadcn@latest add button input table form dialog select card tabs

            # Install additional deps
            $PKG_MANAGER add @supabase/supabase-js @supabase/ssr zustand
            $PKG_MANAGER add react-hook-form @hookform/resolvers zod
            $PKG_MANAGER add clsx tailwind-merge class-variance-authority
            $PKG_MANAGER add lucide-react date-fns nanoid
            ;;

        umi-antd-pro)
            echo -e "${BLUE}Creating UmiJS + Ant Design Pro project...${NC}"
            npm create umi -- "$PROJECT_NAME"
            cd "$PROJECT_NAME"

            $PKG_MANAGER add @supabase/supabase-js
            $PKG_MANAGER add date-fns lodash-es
            $PKG_MANAGER add -D @types/lodash-es
            ;;

        expo-nativewind)
            echo -e "${BLUE}Creating Expo + NativeWind project...${NC}"
            npx create-expo-app "$PROJECT_NAME" -t expo-template-blank-typescript
            cd "$PROJECT_NAME"

            $PKG_MANAGER add nativewind
            $PKG_MANAGER add -D tailwindcss
            npx tailwindcss init

            $PKG_MANAGER add @tanstack/react-query @supabase/supabase-js zustand
            ;;

        monorepo)
            echo -e "${BLUE}Creating Bun + Turborepo monorepo...${NC}"
            bunx create-turbo@latest "$PROJECT_NAME"
            cd "$PROJECT_NAME"
            ;;

        *)
            echo -e "${RED}Unknown stack: $STACK${NC}"
            exit 1
            ;;
    esac
}

# Create project structure
create_structure() {
    echo -e "${BLUE}Creating project structure...${NC}"
    local TODAY
    local NOW
    TODAY="$(date +%Y-%m-%d)"
    NOW="$(date '+%Y-%m-%d %H:%M')"

    mkdir -p docs/reference-configs
    if pi_should_generate_full_docs; then
        mkdir -p docs/architecture
    fi
    mkdir -p tasks/archive
    mkdir -p tasks/contracts
    mkdir -p tasks/reviews
    mkdir -p tasks/notes
    mkdir -p plans/archive
    mkdir -p .ai/context
    mkdir -p .ai/harness/checks
    mkdir -p .ai/harness/handoff
    mkdir -p .ai/harness/failures
    mkdir -p .ai/harness/runs
    mkdir -p .claude/templates
    mkdir -p deploy/env
    mkdir -p deploy/scripts
    mkdir -p deploy/submissions
    mkdir -p deploy/runbooks
    mkdir -p deploy/release-checklists
    mkdir -p deploy/sql
    mkdir -p _ops/env
    mkdir -p _ops/secrets
    mkdir -p _ops/artifacts
    mkdir -p _ops/logs
    mkdir -p _ops/state
    mkdir -p _ops/scratch
    mkdir -p artifacts
    create_contract_directories

    # Create documentation files
    cat > docs/CHANGELOG.md << 'EOF'
# Changelog

All notable changes to this project will be documented in this file.

## [Unreleased]

### Added
- Initial project setup

---
*Format based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/)*
EOF

    cat > tasks/todos.md << EOF
# Deferred Goal Ledger

> **Status**: Backlog
> **Updated**: (initial)
> **Scope**: Medium/long-term goals deferred from active plan execution

Current plan tasks live in the active plan's \`## Task Breakdown\`.
Do not duplicate that execution checklist here. Record only work intentionally deferred beyond this slice, with the tradeoff and revisit trigger.

## Deferred Goals

| Goal | Why Deferred | Tradeoff | Revisit Trigger |
|------|--------------|----------|-----------------|
| (none) | No deferred medium/long-term goal recorded yet. | Keep the first sprint bounded. | Add a row when a real follow-up is postponed. |
EOF

    cat > tasks/current.md << EOF
# Current Status Snapshot

<!-- generated-by: repo-harness refresh-current-status v1 -->
<!-- updated_at: bootstrap -->
<!-- stale_after: 24h -->

> **Status**: Idle
> **Updated At**: bootstrap
> **Source Branch**: main
> **Source Commit**: bootstrap
> **Target Branch**: main
> **Stale After**: 24h
> **Reason**: bootstrap
> **Derived From**: active-plan, workstreams, handoff, checks, git status

This file is a tracked mainline snapshot derived from repo artifacts. It is not a live lock, not a kanban board, and not an implementation gate. If it is stale, read the source artifacts below.
EOF

    cat > tasks/lessons.md << EOF
# Lessons Learned (Self-Improvement Loop)

> Capture correction-derived prevention rules here.
> Promote repeated patterns into durable project rules during spa day.

## Template
- Date:
- Triggered by correction:
- Mistake pattern:
- Prevention rule:
- Where to apply next time:
EOF

    pi_install_templates "$PWD" "$ASSETS_TEMPLATES_DIR" "apply"

    mkdir -p docs/researches
    cat > docs/researches/README.md << EOF
# Research Reports

Durable research reports live in this directory as topic-scoped Markdown files.

Use \`YYYYMMDD-topic.md\` names when chronology matters, or \`<topic>.md\` for
stable subject reports. Keep task-local implementation decisions in
\`tasks/notes/\`, and keep repeated correction-derived rules in \`tasks/lessons.md\`.
EOF

    local helper_names
    helper_names="$(pi_workflow_contract_query_lines "$ASSETS_WORKFLOW_CONTRACT" "helpers.scripts" | xargs)"
    pi_install_helpers "$PWD" "$ASSETS_TEMPLATES_DIR/helpers" "apply" "$helper_names"
    install_workflow_contract
    if pi_should_enable_factor_factory "$(pi_plan_type "$STACK")"; then
        pi_install_factor_factory "$PWD" "$ASSETS_FACTOR_FACTORY_DIR" "$SCRIPT_DIR" "apply"
    fi
    ensure_task_sync_package_script
    # Canonical harness state surface:
    # - .ai/context/context-map.json
    # - .ai/harness/policy.json
    # - .ai/harness/brain-manifest.json
    # - .ai/harness/checks/latest.json
    # - .ai/harness/events.jsonl
    # - .ai/harness/architecture/events.jsonl
    # - .ai/harness/handoff/current.md
    # - .ai/harness/handoff/resume.md
    # - .ai/harness/failures/latest.jsonl
    # - .ai/harness/security/.gitkeep
    # - .ai/harness/worktrees/.gitkeep
    # - .ai/harness/runs/.gitkeep
    pi_ensure_harness_state_surface "$PWD" "apply"

    install_hook_settings_template

    install_hook_assets

    if [ -d "$ASSETS_REF_DIR" ]; then
        pi_install_reference_configs "$PWD" "$ASSETS_REF_DIR" "apply"
    else
        pi_write_reference_config_stub "docs/reference-configs/agentic-development-flow.md" "agentic-development-flow.md" "$SCRIPT_DIR/../assets/reference-configs"
        pi_write_reference_config_stub "docs/reference-configs/external-tooling.md" "external-tooling.md" "$SCRIPT_DIR/../assets/reference-configs"
    fi

    # Update .gitignore with explicit entries only
    touch .gitignore
    ensure_gitignore_entry .gitignore "# Project-specific"
    ensure_gitignore_entry .gitignore "artifacts/"
    ensure_gitignore_entry .gitignore "coverage/"
    ensure_gitignore_entry .gitignore "*.tar.gz"
    ensure_gitignore_entry .gitignore "*.tgz"
    ensure_gitignore_entry .gitignore ""
    ensure_gitignore_entry .gitignore "# External references"
    ensure_gitignore_entry .gitignore "_ref/"
    ensure_gitignore_entry .gitignore ".archcontext/"
    ensure_gitignore_entry .gitignore ".codegraph/"
    ensure_gitignore_entry .gitignore ""
    ensure_gitignore_entry .gitignore "# Local operations state"
    ensure_gitignore_entry .gitignore "_ops/"
    ensure_gitignore_entry .gitignore ""
    ensure_gitignore_entry .gitignore "# Environment"
    ensure_gitignore_entry .gitignore ".env"
    ensure_gitignore_entry .gitignore ".env.*"
    ensure_gitignore_entry .gitignore "!.env.example"
    ensure_gitignore_entry .gitignore ""
    ensure_gitignore_entry .gitignore "# OS metadata"
    ensure_gitignore_entry .gitignore ".DS_Store"
    ensure_runtime_gitignore_block .gitignore

    touch deploy/env/.gitkeep
    touch deploy/scripts/.gitkeep
    touch deploy/submissions/.gitkeep
    touch deploy/runbooks/.gitkeep
    touch deploy/release-checklists/.gitkeep
    touch deploy/sql/.gitkeep
    if [[ ! -f deploy/README.md ]]; then
        cat > deploy/README.md << 'EOF'
# Deployment Operations

`deploy/` is a commit-ready surface for deployment and operations runbooks, submission materials, release checklists, helper scripts, and env examples.

## Track

- `deploy/scripts/` for operational scripts.
- `deploy/submissions/` for submission or review materials.
- `deploy/runbooks/` and `deploy/release-checklists/` for operational documentation.
- `deploy/sql/` as the default SQL root for ordered files named like `0001_create_tables.sql`.
- `deploy/*.md` for runbooks and operating notes.
- `deploy/env/.env.example` for documented variable shapes only.

If `.ai/harness/policy.json` defines `operations.deploy_sql`, its roots, naming modes, and `invariant_file` are the sole authority for an established alternate SQL layout. When it is absent, SQL files remain direct children of `deploy/sql/` with `ordered4` names.

## Do Not Track

- `_ops/`
- private keys, real env files, provider state, production tokens, credential dumps, artifacts, logs, and local-only overrides

Keep external upstream checkouts and source references in `_ref/`; `_ref/` is ignored and must stay out of commits.
EOF
    fi

    # Create .env.example
    cat > .env.example << 'EOF'
# Supabase
SUPABASE_URL=https://your-project.supabase.co
SUPABASE_ANON_KEY=your-anon-key

# Optional: Service Role (server-side only)
# SUPABASE_SERVICE_ROLE_KEY=your-service-role-key

# App Config
NODE_ENV=development
PORT=3000
EOF

    echo -e "${GREEN}Project structure created!${NC}"
}

# Install dev tools
install_dev_tools() {
    echo -e "${BLUE}Installing dev tools...${NC}"

    # Biome (Linting & Formatting)
    $PKG_MANAGER add -D @biomejs/biome

    # Testing
    $PKG_MANAGER add -D vitest @testing-library/react @testing-library/jest-dom

    # Initialize Biome
    npx @biomejs/biome init

    echo -e "${GREEN}Dev tools installed!${NC}"
}

# Write version stamp into the generated project
write_version_stamp() {
    local skill_version_file="$SCRIPT_DIR/../assets/skill-version.json"
    local stamp_dir=".claude"
    local stamp_file="$stamp_dir/.skill-version"
    local sv_version="unknown"
    local sv_template_version="unknown"

    if [ -f "$skill_version_file" ] && command_exists bun; then
        sv_version=$(bun -e "console.log(JSON.parse(require('fs').readFileSync('$skill_version_file','utf-8')).version)")
        sv_template_version=$(bun -e "console.log(JSON.parse(require('fs').readFileSync('$skill_version_file','utf-8')).templateVersion)")
    elif [ -f "$skill_version_file" ] && command_exists node; then
        sv_version=$(node -e "console.log(JSON.parse(require('fs').readFileSync('$skill_version_file','utf-8')).version)")
        sv_template_version=$(node -e "console.log(JSON.parse(require('fs').readFileSync('$skill_version_file','utf-8')).templateVersion)")
    fi

    mkdir -p "$stamp_dir"
    cat > "$stamp_file" << STAMP_EOF
skill_version=$sv_version
template_version=$sv_template_version
generated_at=$(date -u '+%Y-%m-%dT%H:%M:%SZ')
plan_type=${STACK}
STAMP_EOF
    echo -e "${GREEN}Version stamp written to $stamp_file${NC}"
}

# Run a skill lifecycle hook (if bun is available)
run_skill_hook() {
    local event="$1"
    local hook_script="$SCRIPT_DIR/run-skill-hook.ts"

    if command_exists bun && [ -f "$hook_script" ]; then
        bun "$hook_script" "$event" --context "{\"projectName\":\"$PROJECT_NAME\",\"stack\":\"$STACK\"}" 2>&1 || {
            if [[ "$event" == pre-* ]]; then
                echo -e "${RED}Pre-hook $event failed, aborting.${NC}"
                return 1
            else
                echo -e "${YELLOW}Post-hook $event warning (non-fatal).${NC}"
            fi
        }
    fi
}

# Main execution
main() {
    run_skill_hook "pre-init" || exit 1

    check_package_manager
    create_project
    create_structure
    install_dev_tools
    write_version_stamp

    run_skill_hook "post-init"

    echo ""
    echo -e "${GREEN}=== Project initialized successfully! ===${NC}"
    echo ""
    echo "Next steps:"
    echo "  1. cd $PROJECT_NAME"
    echo "  2. Copy .env.example to .env and configure"
    echo "  3. Run: $PKG_MANAGER run dev"
    echo "  4. Use Codex Plan mode or Waza /think, then capture it with: repo-harness run capture-plan --slug first-feature --title \"First Feature\""
    echo "  5. After approval, run: repo-harness run plan-to-todo --plan <active-plan>"
    echo ""
    pi_maybe_install_agent_fleet "$PWD" "apply" "$SCRIPT_DIR/install-agent-fleet.sh"
    pi_print_external_tooling_report "$PWD" "apply" "$SCRIPT_DIR/check-agent-tooling.sh"
    echo ""
}

if [[ "$(pi_env_value "REPO_HARNESS_SOURCE_ONLY" "0")" != "1" ]]; then
    main
fi
